/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FavoriteMovieCard: typeof import('./src/components/FavoriteMovieCard.vue')['default']
    FavoritesList: typeof import('./src/components/FavoritesList.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    MovieDetails: typeof import('./src/components/MovieDetails.vue')['default']
    MovieGrid: typeof import('./src/components/MovieGrid.vue')['default']
    MovieSearch: typeof import('./src/components/MovieSearch.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
